# Global settings applied to the whole site.
NPM_VERSION = "5.4.2"
[context.production.environment]
  HUGO_VERSION = "0.27"
# you can lock a version of hugo for a deploy preview
[context.deploy-preview.environment]
  HUGO_VERSION = "0.27"

[build]
  command = "gulp build"
  publish = "dist"
